INSERT INTO eq_suggestions (emotion, activity_text) VALUES
  ('anxious',     'Try a 5-minute box breathing exercise'),
  ('anxious',     'Write down what you''re afraid of, then what''s most likely to happen'),
  ('anxious',     'Go for a 10-minute walk without your phone'),
  ('overwhelmed', 'Pick ONE thing to do and ignore the rest for now'),
  ('overwhelmed', 'Write a brain dump — everything in your head, onto paper'),
  ('overwhelmed', 'Take a 20-minute break completely away from screens'),
  ('sad',         'Call or message someone you feel safe with'),
  ('sad',         'Put on a comfort playlist and let yourself feel it'),
  ('sad',         'Do something small and physical — tidy one corner, stretch, cook'),
  ('angry',       'Write a letter you won''t send'),
  ('angry',       'Do something physical — run, dance, punch a pillow'),
  ('angry',       'Give yourself 10 minutes before responding to the trigger'),
  ('numb',        'Go outside and notice 5 things you can see, 4 you can touch'),
  ('numb',        'Make a warm drink and sit with it slowly'),
  ('numb',        'Watch or read something that usually moves you'),
  ('hopeful',     'Write down three things you''re looking forward to'),
  ('hopeful',     'Share your hope with someone — it gets stronger out loud'),
  ('hopeful',     'Take one small step toward whatever you''re hopeful about'),
  ('grateful',    'Write three specific things you''re grateful for today'),
  ('grateful',    'Tell someone you appreciate them — be specific why'),
  ('grateful',    'Do something kind for someone without telling them'),
  ('lonely',      'Reach out to one person, even just to say hi'),
  ('lonely',      'Go somewhere with people around — a café, library, park'),
  ('lonely',      'Do something you love that connects you to yourself'),
  ('stuck',       'Change your physical environment — different room, go outside'),
  ('stuck',       'Set a 10-minute timer and just start — not to finish, just to start'),
  ('stuck',       'Ask yourself: what''s the smallest possible next step?'),
  ('excited',     'Write down what''s exciting so you don''t lose the energy'),
  ('excited',     'Channel it — start something you''ve been putting off'),
  ('excited',     'Share it! Excitement multiplies when expressed');
