import { EqSuggestion } from './models';

/**
 * Reference data bundled with the app (REQ-SEED-07): identical for everyone,
 * needs no table, and works with no network.
 *
 * 39 emotions. Deliberately includes the ones that are hard to name -- numb,
 * flat, resentful, envious, ashamed, wired -- because those are exactly the
 * ones a person cannot look up while inside them. Also the ordinary ones:
 * tired, bored, fine, meh, and 'frustrated', which is not the same as stuck or
 * angry and is most of debugging (REQ-SEED-04).
 *
 * Suggestions answer their own emotion: what helps anger is not what helps
 * numbness. Anything needing another person has a sibling that does not, since
 * "there is nobody right now" must never read as a failing (REQ-SEED-09).
 * Nothing here carries a medical claim (REQ-SEED-10).
 *
 * The 'general' set is the fallback for an emotion typed by hand that this
 * list has never heard of (REQ-EQ-03).
 */
export const EQ_SUGGESTIONS: EqSuggestion[] = [
  { id: "anxious-1", emotion: "anxious", activity_text: "Make your out-breath longer" },
  { id: "anxious-2", emotion: "anxious", activity_text: "Write the worry down word for word" },
  { id: "anxious-3", emotion: "anxious", activity_text: "Name the most likely outcome" },
  { id: "anxious-4", emotion: "anxious", activity_text: "Press feet flat on floor" },
  { id: "anxious-5", emotion: "anxious", activity_text: "Walk one lap outside" },
  { id: "anxious-6", emotion: "anxious", activity_text: "Unclench your jaw" },
  { id: "anxious-7", emotion: "anxious", activity_text: "Postpone it to a set time" },
  { id: "wired-1", emotion: "wired", activity_text: "Two sighs, long slow exhale" },
  { id: "wired-2", emotion: "wired", activity_text: "Dim the lights around you" },
  { id: "wired-3", emotion: "wired", activity_text: "Put the phone in another room" },
  { id: "wired-4", emotion: "wired", activity_text: "Run warm water over hands" },
  { id: "wired-5", emotion: "wired", activity_text: "Stretch your arms overhead slowly" },
  { id: "wired-6", emotion: "wired", activity_text: "Lie down for three minutes" },
  { id: "wired-7", emotion: "wired", activity_text: "Turn off notifications until morning" },
  { id: "wired-8", emotion: "wired", activity_text: "Step outside into cooler air" },
  { id: "restless-1", emotion: "restless", activity_text: "Shake out hands and shoulders" },
  { id: "restless-2", emotion: "restless", activity_text: "Take the stairs twice" },
  { id: "restless-3", emotion: "restless", activity_text: "Ten push-ups against the wall" },
  { id: "restless-4", emotion: "restless", activity_text: "Walk while you think" },
  { id: "restless-5", emotion: "restless", activity_text: "Tidy one surface, then stop" },
  { id: "restless-6", emotion: "restless", activity_text: "Put music on and move" },
  { id: "restless-7", emotion: "restless", activity_text: "Step outside for five minutes" },
  { id: "dread-1", emotion: "dread", activity_text: "Name the thing you are avoiding" },
  { id: "dread-2", emotion: "dread", activity_text: "Write down when it actually happens" },
  { id: "dread-3", emotion: "dread", activity_text: "Do the first two minutes" },
  { id: "dread-4", emotion: "dread", activity_text: "Tell someone what you dread" },
  { id: "dread-5", emotion: "dread", activity_text: "Ask what the worst realistically is" },
  { id: "dread-6", emotion: "dread", activity_text: "Check the actual deadline" },
  { id: "dread-7", emotion: "dread", activity_text: "Put it in the calendar" },
  { id: "numb-1", emotion: "numb", activity_text: "Wash your face, cold water" },
  { id: "numb-2", emotion: "numb", activity_text: "Name five things you see" },
  { id: "numb-3", emotion: "numb", activity_text: "Press palms together firmly" },
  { id: "numb-4", emotion: "numb", activity_text: "Eat something with strong flavour" },
  { id: "numb-5", emotion: "numb", activity_text: "Notice your feet on the ground" },
  { id: "numb-6", emotion: "numb", activity_text: "Make a warm drink slowly" },
  { id: "numb-7", emotion: "numb", activity_text: "Put on a song you know" },
  { id: "numb-8", emotion: "numb", activity_text: "Text one person a plain hello" },
  { id: "flat-1", emotion: "flat", activity_text: "Let more light in" },
  { id: "flat-2", emotion: "flat", activity_text: "Stand in daylight ten minutes" },
  { id: "flat-3", emotion: "flat", activity_text: "Start one small chore" },
  { id: "flat-4", emotion: "flat", activity_text: "Change into fresh clothes" },
  { id: "flat-5", emotion: "flat", activity_text: "Play one loud favourite song" },
  { id: "flat-6", emotion: "flat", activity_text: "Make food you like" },
  { id: "flat-7", emotion: "flat", activity_text: "Message someone about something small" },
  { id: "sad-1", emotion: "sad", activity_text: "Let the tears come" },
  { id: "sad-2", emotion: "sad", activity_text: "Put on a comfort playlist" },
  { id: "sad-3", emotion: "sad", activity_text: "Message someone who feels safe" },
  { id: "sad-4", emotion: "sad", activity_text: "Wrap up in a blanket" },
  { id: "sad-5", emotion: "sad", activity_text: "Write what you are missing" },
  { id: "sad-6", emotion: "sad", activity_text: "Watch something you already love" },
  { id: "sad-7", emotion: "sad", activity_text: "Walk slowly with no destination" },
  { id: "lonely-1", emotion: "lonely", activity_text: "Text one person a photo" },
  { id: "lonely-2", emotion: "lonely", activity_text: "Reply to an old message" },
  { id: "lonely-3", emotion: "lonely", activity_text: "Ask someone a real question" },
  { id: "lonely-4", emotion: "lonely", activity_text: "Sit somewhere with people around" },
  { id: "lonely-5", emotion: "lonely", activity_text: "Put a familiar voice on" },
  { id: "lonely-6", emotion: "lonely", activity_text: "Cook something someone taught you" },
  { id: "lonely-7", emotion: "lonely", activity_text: "Write to someone without sending" },
  { id: "hurt-1", emotion: "hurt", activity_text: "Name exactly what stung" },
  { id: "hurt-2", emotion: "hurt", activity_text: "Write the sentence you heard" },
  { id: "hurt-3", emotion: "hurt", activity_text: "Tell one person what happened" },
  { id: "hurt-4", emotion: "hurt", activity_text: "Wait an hour before replying" },
  { id: "hurt-5", emotion: "hurt", activity_text: "Hand on chest, breathe out" },
  { id: "hurt-6", emotion: "hurt", activity_text: "Make yourself the good coffee" },
  { id: "hurt-7", emotion: "hurt", activity_text: "Step away from the conversation" },
  { id: "disappointed-1", emotion: "disappointed", activity_text: "Write down what you expected" },
  { id: "disappointed-2", emotion: "disappointed", activity_text: "Say the disappointment out loud" },
  { id: "disappointed-3", emotion: "disappointed", activity_text: "Ask what is still possible" },
  { id: "disappointed-4", emotion: "disappointed", activity_text: "Tell someone the honest version" },
  { id: "disappointed-5", emotion: "disappointed", activity_text: "Do one thing you control" },
  { id: "disappointed-6", emotion: "disappointed", activity_text: "Close the tab, walk away" },
  { id: "disappointed-7", emotion: "disappointed", activity_text: "Sketch a rough next attempt" },
  { id: "angry-1", emotion: "angry", activity_text: "Slow the exhale, count six" },
  { id: "angry-2", emotion: "angry", activity_text: "Wait ten minutes before replying" },
  { id: "angry-3", emotion: "angry", activity_text: "Write the message, do not send" },
  { id: "angry-4", emotion: "angry", activity_text: "Walk until the heat drops" },
  { id: "angry-5", emotion: "angry", activity_text: "Name the boundary that got crossed" },
  { id: "angry-6", emotion: "angry", activity_text: "Drink cold water slowly" },
  { id: "angry-7", emotion: "angry", activity_text: "Say what you actually want" },
  { id: "angry-8", emotion: "angry", activity_text: "Leave the room for five" },
  { id: "irritable-1", emotion: "irritable", activity_text: "Check when you last ate" },
  { id: "irritable-2", emotion: "irritable", activity_text: "Drink water before deciding anything" },
  { id: "irritable-3", emotion: "irritable", activity_text: "Put headphones on, block noise" },
  { id: "irritable-4", emotion: "irritable", activity_text: "Ten minutes alone, door closed" },
  { id: "irritable-5", emotion: "irritable", activity_text: "Lower the screen brightness" },
  { id: "irritable-6", emotion: "irritable", activity_text: "Postpone the annoying conversation" },
  { id: "irritable-7", emotion: "irritable", activity_text: "Open a window, stand there" },
  { id: "resentful-1", emotion: "resentful", activity_text: "Write who owes you what" },
  { id: "resentful-2", emotion: "resentful", activity_text: "Name the ask you never made" },
  { id: "resentful-3", emotion: "resentful", activity_text: "Say no to one thing today" },
  { id: "resentful-4", emotion: "resentful", activity_text: "Check whether they actually know" },
  { id: "resentful-5", emotion: "resentful", activity_text: "Draft the request in plain words" },
  { id: "resentful-6", emotion: "resentful", activity_text: "List what you quietly took on" },
  { id: "resentful-7", emotion: "resentful", activity_text: "Hand one task back tomorrow" },
  { id: "envious-1", emotion: "envious", activity_text: "Name what you actually want" },
  { id: "envious-2", emotion: "envious", activity_text: "Mute the account for a week" },
  { id: "envious-3", emotion: "envious", activity_text: "Write the one thing you envy" },
  { id: "envious-4", emotion: "envious", activity_text: "Ask what step they took" },
  { id: "envious-5", emotion: "envious", activity_text: "List what you did this year" },
  { id: "envious-6", emotion: "envious", activity_text: "Notice what you cannot see" },
  { id: "envious-7", emotion: "envious", activity_text: "Turn it into one small goal" },
  { id: "ashamed-1", emotion: "ashamed", activity_text: "Tell one person you trust" },
  { id: "ashamed-2", emotion: "ashamed", activity_text: "Write it down, plainly" },
  { id: "ashamed-3", emotion: "ashamed", activity_text: "Separate the act from you" },
  { id: "ashamed-4", emotion: "ashamed", activity_text: "Ask what repair is possible" },
  { id: "ashamed-5", emotion: "ashamed", activity_text: "Do the smallest repair now" },
  { id: "ashamed-6", emotion: "ashamed", activity_text: "Speak to yourself as a friend" },
  { id: "ashamed-7", emotion: "ashamed", activity_text: "Return to one ordinary task" },
  { id: "guilty-1", emotion: "guilty", activity_text: "Name what actually happened" },
  { id: "guilty-2", emotion: "guilty", activity_text: "Apologise in one plain sentence" },
  { id: "guilty-3", emotion: "guilty", activity_text: "Ask what would make amends" },
  { id: "guilty-4", emotion: "guilty", activity_text: "Repair it when you can" },
  { id: "guilty-5", emotion: "guilty", activity_text: "Check the standard was fair" },
  { id: "guilty-6", emotion: "guilty", activity_text: "Write what you will do differently" },
  { id: "guilty-7", emotion: "guilty", activity_text: "Let the rest go for now" },
  { id: "insecure-1", emotion: "insecure", activity_text: "Name the skill you are learning" },
  { id: "insecure-2", emotion: "insecure", activity_text: "Write what you already shipped" },
  { id: "insecure-3", emotion: "insecure", activity_text: "Ask the question you are hiding" },
  { id: "insecure-4", emotion: "insecure", activity_text: "Compare to your own last year" },
  { id: "insecure-5", emotion: "insecure", activity_text: "Say you do not know yet" },
  { id: "insecure-6", emotion: "insecure", activity_text: "Keep a small win log" },
  { id: "insecure-7", emotion: "insecure", activity_text: "Pair with someone for an hour" },
  { id: "overwhelmed-1", emotion: "overwhelmed", activity_text: "Brain dump everything onto paper" },
  { id: "overwhelmed-2", emotion: "overwhelmed", activity_text: "Pick one thing, ignore the rest" },
  { id: "overwhelmed-3", emotion: "overwhelmed", activity_text: "Set a ten minute timer" },
  { id: "overwhelmed-4", emotion: "overwhelmed", activity_text: "Close every tab but one" },
  { id: "overwhelmed-5", emotion: "overwhelmed", activity_text: "Cancel one thing today" },
  { id: "overwhelmed-6", emotion: "overwhelmed", activity_text: "Ask for help with one item" },
  { id: "overwhelmed-7", emotion: "overwhelmed", activity_text: "Step away from screens completely" },
  { id: "overwhelmed-8", emotion: "overwhelmed", activity_text: "Write tomorrow's three, then stop" },
  { id: "stuck-1", emotion: "stuck", activity_text: "Name the smallest next action" },
  { id: "stuck-2", emotion: "stuck", activity_text: "Set a timer, start badly" },
  { id: "stuck-3", emotion: "stuck", activity_text: "Move to a different room" },
  { id: "stuck-4", emotion: "stuck", activity_text: "Explain the problem out loud" },
  { id: "stuck-5", emotion: "stuck", activity_text: "Write the problem in one sentence" },
  { id: "stuck-6", emotion: "stuck", activity_text: "Do two minutes, then stop" },
  { id: "stuck-7", emotion: "stuck", activity_text: "Open the file, nothing more" },
  { id: "stuck-8", emotion: "stuck", activity_text: "Go for a short walk" },
  { id: "drained-1", emotion: "drained", activity_text: "Stop at the next natural break" },
  { id: "drained-2", emotion: "drained", activity_text: "Lower the bar for today" },
  { id: "drained-3", emotion: "drained", activity_text: "Eat whatever is easiest" },
  { id: "drained-4", emotion: "drained", activity_text: "Lie down without your phone" },
  { id: "drained-5", emotion: "drained", activity_text: "Turn the lights down low" },
  { id: "drained-6", emotion: "drained", activity_text: "Sleep earlier than you planned" },
  { id: "drained-7", emotion: "drained", activity_text: "Do only what is due today" },
  { id: "hopeful-1", emotion: "hopeful", activity_text: "Let yourself want it" },
  { id: "hopeful-2", emotion: "hopeful", activity_text: "Write what you are hoping for" },
  { id: "hopeful-3", emotion: "hopeful", activity_text: "Picture it going well" },
  { id: "hopeful-4", emotion: "hopeful", activity_text: "Name what is still uncertain" },
  { id: "hopeful-5", emotion: "hopeful", activity_text: "Focus on the part you control" },
  { id: "hopeful-6", emotion: "hopeful", activity_text: "Remember a time it worked" },
  { id: "hopeful-7", emotion: "hopeful", activity_text: "Keep it to yourself for now" },
  { id: "excited-1", emotion: "excited", activity_text: "Enjoy it before doing anything" },
  { id: "excited-2", emotion: "excited", activity_text: "Write it down before it fades" },
  { id: "excited-3", emotion: "excited", activity_text: "Start the first small piece" },
  { id: "excited-4", emotion: "excited", activity_text: "Tell one person about it" },
  { id: "excited-5", emotion: "excited", activity_text: "Keep going while it lasts" },
  { id: "excited-6", emotion: "excited", activity_text: "Make a rough sketch now" },
  { id: "excited-7", emotion: "excited", activity_text: "Notice what made it click" },
  { id: "curious-1", emotion: "curious", activity_text: "Write the question down" },
  { id: "curious-2", emotion: "curious", activity_text: "Let the question sit unanswered" },
  { id: "curious-3", emotion: "curious", activity_text: "Follow it for fifteen minutes" },
  { id: "curious-4", emotion: "curious", activity_text: "Read one article end to end" },
  { id: "curious-5", emotion: "curious", activity_text: "Open a scratch project" },
  { id: "curious-6", emotion: "curious", activity_text: "Try it in code first" },
  { id: "curious-7", emotion: "curious", activity_text: "Ask someone who would know" },
  { id: "curious-8", emotion: "curious", activity_text: "Note what surprised you" },
  { id: "content-1", emotion: "content", activity_text: "Sit with it a moment" },
  { id: "content-2", emotion: "content", activity_text: "Notice what made today easy" },
  { id: "content-3", emotion: "content", activity_text: "Take a photo of now" },
  { id: "content-4", emotion: "content", activity_text: "Write one line about today" },
  { id: "content-5", emotion: "content", activity_text: "Tell someone you feel good" },
  { id: "content-6", emotion: "content", activity_text: "Let the day be enough" },
  { id: "content-7", emotion: "content", activity_text: "Remember this for a harder day" },
  { id: "calm-1", emotion: "calm", activity_text: "Notice where the calm sits" },
  { id: "calm-2", emotion: "calm", activity_text: "Breathe without changing anything" },
  { id: "calm-3", emotion: "calm", activity_text: "Add nothing new right now" },
  { id: "calm-4", emotion: "calm", activity_text: "Do one task slowly" },
  { id: "calm-5", emotion: "calm", activity_text: "Read something for pleasure" },
  { id: "calm-6", emotion: "calm", activity_text: "Stay off the news feeds" },
  { id: "calm-7", emotion: "calm", activity_text: "Write a note to future you" },
  { id: "grateful-1", emotion: "grateful", activity_text: "Write three specific things" },
  { id: "grateful-2", emotion: "grateful", activity_text: "Tell someone exactly why" },
  { id: "grateful-3", emotion: "grateful", activity_text: "Send a two line thank you" },
  { id: "grateful-4", emotion: "grateful", activity_text: "Do a quiet favour today" },
  { id: "grateful-5", emotion: "grateful", activity_text: "Say it out loud once" },
  { id: "grateful-6", emotion: "grateful", activity_text: "Note who helped this week" },
  { id: "grateful-7", emotion: "grateful", activity_text: "Thank someone you usually forget" },
  { id: "proud-1", emotion: "proud", activity_text: "Write down what you did" },
  { id: "proud-2", emotion: "proud", activity_text: "Let it land before moving on" },
  { id: "proud-3", emotion: "proud", activity_text: "Say it out loud once" },
  { id: "proud-4", emotion: "proud", activity_text: "Note the skill you used" },
  { id: "proud-5", emotion: "proud", activity_text: "Save the evidence somewhere" },
  { id: "proud-6", emotion: "proud", activity_text: "Do something you enjoy next" },
  { id: "proud-7", emotion: "proud", activity_text: "Thank whoever helped you" },
  { id: "relieved-1", emotion: "relieved", activity_text: "Let your shoulders drop" },
  { id: "relieved-2", emotion: "relieved", activity_text: "Say out loud, that is done" },
  { id: "relieved-3", emotion: "relieved", activity_text: "Note what actually helped" },
  { id: "relieved-4", emotion: "relieved", activity_text: "Rest before starting anything new" },
  { id: "relieved-5", emotion: "relieved", activity_text: "Tell the person who worried" },
  { id: "relieved-6", emotion: "relieved", activity_text: "Close the tab for good" },
  { id: "relieved-7", emotion: "relieved", activity_text: "Do something easy next" },
  { id: "tender-1", emotion: "tender", activity_text: "Let yourself feel it" },
  { id: "tender-2", emotion: "tender", activity_text: "Message the person you thought of" },
  { id: "tender-3", emotion: "tender", activity_text: "Hold something soft" },
  { id: "tender-4", emotion: "tender", activity_text: "Play the song that moved you" },
  { id: "tender-5", emotion: "tender", activity_text: "Write the person a line" },
  { id: "tender-6", emotion: "tender", activity_text: "Look at old photos" },
  { id: "tender-7", emotion: "tender", activity_text: "Say the affectionate thing aloud" },
  { id: "tender-8", emotion: "tender", activity_text: "Move slowly for a while" },
  { id: "frustrated-1", emotion: "frustrated", activity_text: "Read the error slowly, twice" },
  { id: "frustrated-2", emotion: "frustrated", activity_text: "List what you already ruled out" },
  { id: "frustrated-3", emotion: "frustrated", activity_text: "Change one thing, then retest" },
  { id: "frustrated-4", emotion: "frustrated", activity_text: "Return to the last working state" },
  { id: "frustrated-5", emotion: "frustrated", activity_text: "Check the assumption you skipped" },
  { id: "frustrated-6", emotion: "frustrated", activity_text: "Leave it for ten minutes" },
  { id: "frustrated-7", emotion: "frustrated", activity_text: "Ask someone with fresh eyes" },
  { id: "frustrated-8", emotion: "frustrated", activity_text: "Note the progress you did make" },
  { id: "tired-1", emotion: "tired", activity_text: "Lower today's list to three" },
  { id: "tired-2", emotion: "tired", activity_text: "Do the easiest task first" },
  { id: "tired-3", emotion: "tired", activity_text: "Lie down for twenty minutes" },
  { id: "tired-4", emotion: "tired", activity_text: "Eat something warm and simple" },
  { id: "tired-5", emotion: "tired", activity_text: "Open a window, look out" },
  { id: "tired-6", emotion: "tired", activity_text: "Stop screens an hour early" },
  { id: "tired-7", emotion: "tired", activity_text: "Save the hard task for tomorrow" },
  { id: "tired-8", emotion: "tired", activity_text: "Go to bed without finishing" },
  { id: "bored-1", emotion: "bored", activity_text: "Change where you sit" },
  { id: "bored-2", emotion: "bored", activity_text: "Try one unfamiliar Angular feature" },
  { id: "bored-3", emotion: "bored", activity_text: "Build something small for fun" },
  { id: "bored-4", emotion: "bored", activity_text: "Read something outside your field" },
  { id: "bored-5", emotion: "bored", activity_text: "Walk without headphones" },
  { id: "bored-6", emotion: "bored", activity_text: "Tidy your dev setup" },
  { id: "bored-7", emotion: "bored", activity_text: "Ask someone what they are building" },
  { id: "bored-8", emotion: "bored", activity_text: "Write down what sounds interesting" },
  { id: "confused-1", emotion: "confused", activity_text: "Write what you do understand" },
  { id: "confused-2", emotion: "confused", activity_text: "List the exact unknowns" },
  { id: "confused-3", emotion: "confused", activity_text: "Draw the flow on paper" },
  { id: "confused-4", emotion: "confused", activity_text: "Read the docs from the start" },
  { id: "confused-5", emotion: "confused", activity_text: "Find one small working example" },
  { id: "confused-6", emotion: "confused", activity_text: "Say what you expected to happen" },
  { id: "confused-7", emotion: "confused", activity_text: "Break it into two questions" },
  { id: "confused-8", emotion: "confused", activity_text: "Ask the plain beginner question" },
  { id: "fine-1", emotion: "fine", activity_text: "Let fine be enough today" },
  { id: "fine-2", emotion: "fine", activity_text: "Ask what fine is covering" },
  { id: "fine-3", emotion: "fine", activity_text: "Check if you are simply tired" },
  { id: "fine-4", emotion: "fine", activity_text: "Keep the usual routine today" },
  { id: "fine-5", emotion: "fine", activity_text: "Do one thing you like" },
  { id: "fine-6", emotion: "fine", activity_text: "Write one honest line" },
  { id: "fine-7", emotion: "fine", activity_text: "Note it and move on" },
  { id: "okay-1", emotion: "okay", activity_text: "Do the next ordinary thing" },
  { id: "okay-2", emotion: "okay", activity_text: "Note what makes days okay" },
  { id: "okay-3", emotion: "okay", activity_text: "Clear one small overdue task" },
  { id: "okay-4", emotion: "okay", activity_text: "Spend an hour learning something" },
  { id: "okay-5", emotion: "okay", activity_text: "Keep the bar exactly here" },
  { id: "okay-6", emotion: "okay", activity_text: "Enjoy an unremarkable evening" },
  { id: "okay-7", emotion: "okay", activity_text: "Fix one thing that annoys you" },
  { id: "meh-1", emotion: "meh", activity_text: "Let a plain day be plain" },
  { id: "meh-2", emotion: "meh", activity_text: "Change what you listen to" },
  { id: "meh-3", emotion: "meh", activity_text: "Do something with your hands" },
  { id: "meh-4", emotion: "meh", activity_text: "Start something you can abandon" },
  { id: "meh-5", emotion: "meh", activity_text: "Go somewhere slightly different" },
  { id: "meh-6", emotion: "meh", activity_text: "Eat something you actually chose" },
  { id: "meh-7", emotion: "meh", activity_text: "Look up something you wondered about" },
  { id: "meh-8", emotion: "meh", activity_text: "Notice one thing worth keeping" },
  { id: "embarrassed-1", emotion: "embarrassed", activity_text: "Say it plainly, then continue" },
  { id: "embarrassed-2", emotion: "embarrassed", activity_text: "Assume they have already forgotten" },
  { id: "embarrassed-3", emotion: "embarrassed", activity_text: "Correct it once, then stop" },
  { id: "embarrassed-4", emotion: "embarrassed", activity_text: "Remember everyone has broken the build" },
  { id: "embarrassed-5", emotion: "embarrassed", activity_text: "Tell someone who will understand" },
  { id: "embarrassed-6", emotion: "embarrassed", activity_text: "Step away from the thread" },
  { id: "embarrassed-7", emotion: "embarrassed", activity_text: "Get back to plain work" },
  { id: "nervous-1", emotion: "nervous", activity_text: "Write your three main points" },
  { id: "nervous-2", emotion: "nervous", activity_text: "Rehearse the first two sentences" },
  { id: "nervous-3", emotion: "nervous", activity_text: "Test your audio and screen" },
  { id: "nervous-4", emotion: "nervous", activity_text: "Arrive a few minutes early" },
  { id: "nervous-5", emotion: "nervous", activity_text: "Keep water within reach" },
  { id: "nervous-6", emotion: "nervous", activity_text: "Slow your first sentence down" },
  { id: "nervous-7", emotion: "nervous", activity_text: "Let the nerves be there" },
  { id: "nervous-8", emotion: "nervous", activity_text: "Plan something easy afterwards" },
  { id: "distracted-1", emotion: "distracted", activity_text: "Write the one task down" },
  { id: "distracted-2", emotion: "distracted", activity_text: "Put the phone out of reach" },
  { id: "distracted-3", emotion: "distracted", activity_text: "Work in short timed blocks" },
  { id: "distracted-4", emotion: "distracted", activity_text: "Keep a list of tangents" },
  { id: "distracted-5", emotion: "distracted", activity_text: "Silence notifications for an hour" },
  { id: "distracted-6", emotion: "distracted", activity_text: "Note the distraction, return anyway" },
  { id: "distracted-7", emotion: "distracted", activity_text: "Read the next line aloud" },
  { id: "general-1", emotion: 'general', activity_text: "Name the feeling out loud, once" },
  { id: "general-2", emotion: 'general', activity_text: "Step outside for five minutes" },
  { id: "general-3", emotion: 'general', activity_text: "Put your feet flat on the floor" },
  { id: "general-4", emotion: 'general', activity_text: "Do the smallest next thing" },
  { id: "general-5", emotion: 'general', activity_text: "Write one plain line about it" },
  { id: "general-6", emotion: 'general', activity_text: "Let it be there for now" },
];

/** Offered as chips, in the order shown. The rest are reachable by typing. */
export const EQ_EMOTIONS: string[] = [
  "anxious",
  "wired",
  "restless",
  "dread",
  "numb",
  "flat",
  "sad",
  "lonely",
  "hurt",
  "disappointed",
  "angry",
  "irritable",
  "resentful",
  "envious",
  "ashamed",
  "guilty",
  "insecure",
  "overwhelmed",
  "stuck",
  "drained",
  "hopeful",
  "excited",
  "curious",
  "content",
  "calm",
  "grateful",
  "proud",
  "relieved",
  "tender",
  "frustrated",
  "tired",
  "bored",
  "confused",
  "fine",
  "okay",
  "meh",
  "embarrassed",
  "nervous",
  "distracted",
];
